config/routes.rb
Rails.application.routes.draw do
  resources :novels
  resources :schools
  resources :awards
  resources :addresses
  resources :authors
  resources :patients
  resources :appointments
  resources :physicians
  resources :accounts
  resources :suppliers
  resources :comments
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account
  include Mongoid::Document
  include Mongoid::Timestamps
  field :acc_no, type: String

  validates :acc_no, presence: true
  belongs_to :supplier
end

app/models/address.rb
class Address
  include Mongoid::Document
  include Mongoid::Timestamps

  field :city
  field :state
  field :country

  belongs_to :place, polymorphic: true
end

app/models/appointment.rb
class Appointment
  include Mongoid::Document
  include Mongoid::Timestamps

  field :time, type: DateTime

  belongs_to :physician
  belongs_to :patient
end

app/models/author.rb
class Author
  include Mongoid::Document
  include Mongoid::Timestamps

  field :first_name
  field :last_name
  field :email
  field :birth_day, type: Date
  field :sex, type: Integer

  has_and_belongs_to_many :novels
  has_many :address, as: :place
  has_many :award, as: :achievement
  has_and_belongs_to_many :schools
end

app/models/award.rb
class Award
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  field :date, type: Date

  belongs_to :achievement, polymorphic: true
  has_one :address, as: :place
end
  

app/models/comment.rb
# frozen_string_literal: true

class Comment
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :message, type: String

  belongs_to :post
end

app/models/novel.rb
class Novel
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  field :price, type: Integer
  field :page, type: Integer

  has_and_belongs_to_many :authors
  has_many :awards, as: :achievement

end

app/models/patient.rb
class Patient
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String

  has_many :appointments

  def physicians
    Physician.in(id: appointments.pluck(:physician_id))
  end
end

app/models/physician.rb
class Physician
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  
  has_many :appointments
  
  def patients
    Patient.in(id: appointments.pluck(:patient_id))
  end
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :body, type: String

  has_many :comments, dependent: :destroy
end

app/models/school.rb
class School
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  field :highest_edu

  has_and_belongs_to_many :authors
  has_one :address, as: :place
  has_many :awards, as: :achievement
end

app/models/supplier.rb
class Supplier
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  validates :name, presence: true
  has_one :account, dependent: :destroy
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.fetch(:school, {})
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper

  def supplier
    @account.new_record? ? params.dig('format') : @account.supplier_id
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/schools/_form.html.erb
<%= form_with(model: school, local: true) do |form| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
        <% school.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schools</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>